call plug#begin('~/.vim/plugged')
Plug 'ervandew/supertab'
Plug 'lervag/vimtex', { 'for': 'tex' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ryanoasis/vim-devicons', { 'on':  'NERDTreeToggle' }
Plug 'tiagofumo/vim-nerdtree-syntax-highlight', { 'on':  'NERDTreeToggle' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'nvie/vim-flake8', { 'for': 'python' }
Plug 'tmhedberg/SimpylFold', { 'for': 'python' }
Plug 'vim-scripts/indentpython.vim', { 'for': 'python' }
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'

if has('nvim')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-jedi', { 'for': 'python' }
endif
call plug#end()

" Map leader key
let mapleader = ","

" Buffer navigation and stuff
noremap <C-left> :bprev<ENTER>
noremap <C-right> :bnext<ENTER>
noremap <Leader>w :bdelete %<ENTER>
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_min_count = 2
set hidden  " Set buffers to hidden. Allows to change buffers without having to save them

" Toggle comments
nmap <C-c> <Plug>CommentaryLine

" Paste from clipboard
nnoremap <Leader>p "0p

" Hex editing
nnoremap <Leader>h :%!xxd<ENTER>
nnoremap <Leader>H :%!xxd -r<ENTER>

" Remove trailing white spaces
nnoremap <Leader>tr :%s/\s\+$//e <BAR> :noh<ENTER> <BAR> :w<ENTER>

if has('nvim')
tnoremap <Esc> <C-\><C-n>
nnoremap <Leader>te :terminal<ENTER>
endif

" Useful stuff
syntax enable
set number
set relativenumber
set encoding=UTF-8
set backupdir=~/.TMP
set background=dark
set shiftwidth=4
set tabstop=4
set scrolloff=1

" Color scheme
color evening
hi Normal ctermbg=None
hi Folded ctermbg=60 ctermfg=2

" Deoplete settings
let g:deoplete#enable_at_startup = 1

" Autopair settings
let g:AutoPairsShortcutToggle = '<M-a>'

" Supertab settings
"let g:SuperTabClosePreviewOnPopupClose = 1

" Vim airline settings
let g:airline_theme='deus'
let g:airline_powerline_fonts = 1
set ttimeoutlen=20

" Nerdtree settings
let NERDTreeNaturalSort=1
let NERDTreeMinimalUI=1
nnoremap <C-n> :NERDTreeToggle<ENTER>

" Devicons settings
"let g:WebDevIconsUnicodeDecorateFolderNodes = 1

" Split settings
set splitbelow
set splitright

" Split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Resizing
nnoremap _ <C-W><C-_>
nnoremap <BAR> :vertical-resize CTRL-W_bar<ENTER>
nnoremap = <C-W><C-=>
nnoremap <down> <C-W><C-->
nnoremap <up> <C-W><C-+>
nnoremap <left> :vertical resize +1<ENTER>
nnoremap <right> :vertical resize -1<ENTER>

" Close preview window
nnoremap <C-z> <C-W><C-z>

" Change directory to match the file's
autocmd BufEnter * silent! lcd %:p:h

" Make sure it understands what .tex means
let g:tex_flavor='latex'

" Disable file specific plugins
let g:vimtex_enable='0'

" Fuck square bracket. Some custom keyboard mappings
set langmap='[,¡],ç=,º`

" Format options.
set textwidth=120
au FileType * set fo-=o fo-=r  " o and r = auto insert comment leader on normal mode and insert mode respectively

" Performance.
set ttyfast
